config/routes.rb
OSUPortal::Application.routes.draw do
  resources :flavors

  devise_for :users

  resources :volumes
  resources :volumes do
    collection do
      post 'delete'
      post 'mount'
    end
  end

  resources :flavors
  resources :rules

  resources :rules do
    collection do
      post 'delete'
    end
  end

  resources :key_pairs

  resources :key_pairs do
    collection do
      post 'delete'
    end
  end
  resources :floating_ips

  resources :floating_ips do
    collection do
      post 'addPublicIP'
      post 'addPrivageIP'
      post 'releasePublicIP'
      post 'releasePrivateIP'
      post 'bindIPtoServer'
      post 'unbindIPtoServer'
    end
  end

  resources :securities
  
  resources :securities do
    collection do
      post 'delete'
    end
  end

  resources :images

  resource :images do
    collection do
      post 'delete'
      end
  end

  resources :os_types

  resources :operating_systems

  resources :hosts

  resources :hosts do
    collection do
      post 'start'
      post 'shutdown'
      post 'softreboot'
      post 'hardreboot'
      post 'emergency_login'
      post 'create_image'
      post 'upgrade'
      post 'reinstall'
      post 'delete'
    end
  end

 

  get "site_skel/home"
  match '/home', to: 'site_skel#home'

  get "site_skel/product"
  match '/product', to: 'site_skel#product'
  
  get "site_skel/about"
  match '/about', to: 'site_skel#about'

  get "site_skel/contact"
  match '/contact', to: 'site_skel#contact'

  match '/', to: 'site_skel#home'

  root :to => 'site_skel#home'

end

app/models/operating_system.rb
class OperatingSystem < ActiveRecord::Base
  attr_accessible :cpuarc, :cpubit, :desc, :name, :os_type_id, :image_id
  belongs_to :os_type
  belongs_to :image
end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < ApplicationController
  before_filter :authenticate_user!

  # GET /operating_systems
  # GET /operating_systems.json
  def index
    @operating_systems = OperatingSystem.all

    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: OperatingSystemDatatable.new(view_context)}
      # format.json  {  render json: {
      #     sEcho: 6,
      #     iTotalRecords: 20,
      #     iTotalDisplayRecords: 6,
      #     aaData: @operating_systems.map do |os|
      #       [
      #        os.name,
      #        os.cpubit,
      #        os.image_id,
      #        os.os_type_id,
      #        os.os_type_id
      #       ]
      #     end
      #   }
      # }
    end
  end

  # GET /operating_systems/1
  # GET /operating_systems/1.json
  def show
    @operating_system = OperatingSystem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operating_system }
    end
  end

  # GET /operating_systems/new
  # GET /operating_systems/new.json
  def new
    @operating_system = OperatingSystem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operating_system }
    end
  end

  # GET /operating_systems/1/edit
  def edit
    @operating_system = OperatingSystem.find(params[:id])
  end

  # POST /operating_systems
  # POST /operating_systems.json
  def create
    @operating_system = OperatingSystem.new(params[:operating_system])

    respond_to do |format|
      if @operating_system.save
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully created.' }
        format.json { render json: @operating_system, status: :created, location: @operating_system }
      else
        format.html { render action: "new" }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operating_systems/1
  # PUT /operating_systems/1.json
  def update
    @operating_system = OperatingSystem.find(params[:id])

    respond_to do |format|
      if @operating_system.update_attributes(params[:operating_system])
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operating_systems/1
  # DELETE /operating_systems/1.json
  def destroy
    @operating_system = OperatingSystem.find(params[:id])
    @operating_system.destroy

    respond_to do |format|
      format.html { redirect_to operating_systems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
end

app/views/operating_systems/_form.html.haml
= form_for @operating_system do |f|
  - if @operating_system.errors.any?
    #error_explanation
      %h2= "#{pluralize(@operating_system.errors.count, "error")} prohibited this operating_system from being saved:"
      %ul
        - @operating_system.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :os_type_id
    = f.number_field :os_type_id
  .field
    = f.label :cpuarc
    = f.text_field :cpuarc
  .field
    = f.label :cpubit
    = f.number_field :cpubit
  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.label :image_id
    = f.text_field :image_id
  .actions
    = f.submit 'Save'

app/views/operating_systems/edit.html.haml
%h1 Editing operating_system

= render 'form'

= link_to 'Show', @operating_system
\|
= link_to 'Back', operating_systems_path

app/views/operating_systems/index.html.haml
%h1 Listing operating_systems

%table
  %tr
    %th Name
    %th Os type
    %th Cpuarc
    %th Cpubit
    %th Desc
    %th
    %th
    %th

  - @operating_systems.each do |operating_system|
    %tr
      %td= operating_system.name
      %td= operating_system.os_type_id
      %td= operating_system.cpuarc
      %td= operating_system.cpubit
      %td= operating_system.desc
      %td= link_to 'Show', operating_system
      %td= link_to 'Edit', edit_operating_system_path(operating_system)
      %td= link_to 'Destroy', operating_system, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Operating system', new_operating_system_path

app/views/operating_systems/new.html.haml
%h1 New operating_system

= render 'form'

= link_to 'Back', operating_systems_path

app/views/operating_systems/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @operating_system.name
%p
  %b Os type:
  = @operating_system.os_type_id
%p
  %b Cpuarc:
  = @operating_system.cpuarc
%p
  %b Cpubit:
  = @operating_system.cpubit
%p
  %b Desc:
  = @operating_system.desc

= link_to 'Edit', edit_operating_system_path(@operating_system)
\|
= link_to 'Back', operating_systems_path