config/routes.rb
OSUPortal::Application.routes.draw do
  resources :flavors

  devise_for :users

  resources :volumes
  resources :volumes do
    collection do
      post 'delete'
      post 'mount'
    end
  end

  resources :flavors
  resources :rules

  resources :rules do
    collection do
      post 'delete'
    end
  end

  resources :key_pairs

  resources :key_pairs do
    collection do
      post 'delete'
    end
  end
  resources :floating_ips

  resources :floating_ips do
    collection do
      post 'addPublicIP'
      post 'addPrivageIP'
      post 'releasePublicIP'
      post 'releasePrivateIP'
      post 'bindIPtoServer'
      post 'unbindIPtoServer'
    end
  end

  resources :securities
  
  resources :securities do
    collection do
      post 'delete'
    end
  end

  resources :images

  resource :images do
    collection do
      post 'delete'
      end
  end

  resources :os_types

  resources :operating_systems

  resources :hosts

  resources :hosts do
    collection do
      post 'start'
      post 'shutdown'
      post 'softreboot'
      post 'hardreboot'
      post 'emergency_login'
      post 'create_image'
      post 'upgrade'
      post 'reinstall'
      post 'delete'
    end
  end

 

  get "site_skel/home"
  match '/home', to: 'site_skel#home'

  get "site_skel/product"
  match '/product', to: 'site_skel#product'
  
  get "site_skel/about"
  match '/about', to: 'site_skel#about'

  get "site_skel/contact"
  match '/contact', to: 'site_skel#contact'

  match '/', to: 'site_skel#home'

  root :to => 'site_skel#home'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  attr_accessible :alias, :flavorid, :memory_mb, :name, :vcpus
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flavors }
    end
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
    @flavor = Flavor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flavor }
    end
  end

  # GET /flavors/new
  # GET /flavors/new.json
  def new
    @flavor = Flavor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flavor }
    end
  end

  # GET /flavors/1/edit
  def edit
    @flavor = Flavor.find(params[:id])
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(params[:flavor])

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render json: @flavor, status: :created, location: @flavor }
      else
        format.html { render action: "new" }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flavors/1
  # PUT /flavors/1.json
  def update
    @flavor = Flavor.find(params[:id])

    respond_to do |format|
      if @flavor.update_attributes(params[:flavor])
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor = Flavor.find(params[:id])
    @flavor.destroy

    respond_to do |format|
      format.html { redirect_to flavors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.haml
= form_for @flavor do |f|
  - if @flavor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@flavor.errors.count, "error")} prohibited this flavor from being saved:"
      %ul
        - @flavor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :alias
    = f.text_field :alias
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :vcpus
    = f.number_field :vcpus
  .field
    = f.label :memory_mb
    = f.number_field :memory_mb
  .field
    = f.label :flavorid
    = f.text_field :flavorid
  .actions
    = f.submit 'Save'

app/views/flavors/edit.html.haml
%h1 Editing flavor

= render 'form'

= link_to 'Show', @flavor
\|
= link_to 'Back', flavors_path

app/views/flavors/index.html.haml
%h1 Listing flavors

%table
  %tr
    %th Alias
    %th Name
    %th Vcpus
    %th Memory mb
    %th Flavorid
    %th
    %th
    %th

  - @flavors.each do |flavor|
    %tr
      %td= flavor.alias
      %td= flavor.name
      %td= flavor.vcpus
      %td= flavor.memory_mb
      %td= flavor.flavorid
      %td= link_to 'Show', flavor
      %td= link_to 'Edit', edit_flavor_path(flavor)
      %td= link_to 'Destroy', flavor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Flavor', new_flavor_path

app/views/flavors/new.html.haml
%h1 New flavor

= render 'form'

= link_to 'Back', flavors_path

app/views/flavors/show.html.haml
%p#notice= notice

%p
  %b Alias:
  = @flavor.alias
%p
  %b Name:
  = @flavor.name
%p
  %b Vcpus:
  = @flavor.vcpus
%p
  %b Memory mb:
  = @flavor.memory_mb
%p
  %b Flavorid:
  = @flavor.flavorid

= link_to 'Edit', edit_flavor_path(@flavor)
\|
= link_to 'Back', flavors_path