config/routes.rb
OSUPortal::Application.routes.draw do
  resources :flavors

  devise_for :users

  resources :volumes
  resources :volumes do
    collection do
      post 'delete'
      post 'mount'
    end
  end

  resources :flavors
  resources :rules

  resources :rules do
    collection do
      post 'delete'
    end
  end

  resources :key_pairs

  resources :key_pairs do
    collection do
      post 'delete'
    end
  end
  resources :floating_ips

  resources :floating_ips do
    collection do
      post 'addPublicIP'
      post 'addPrivageIP'
      post 'releasePublicIP'
      post 'releasePrivateIP'
      post 'bindIPtoServer'
      post 'unbindIPtoServer'
    end
  end

  resources :securities
  
  resources :securities do
    collection do
      post 'delete'
    end
  end

  resources :images

  resource :images do
    collection do
      post 'delete'
      end
  end

  resources :os_types

  resources :operating_systems

  resources :hosts

  resources :hosts do
    collection do
      post 'start'
      post 'shutdown'
      post 'softreboot'
      post 'hardreboot'
      post 'emergency_login'
      post 'create_image'
      post 'upgrade'
      post 'reinstall'
      post 'delete'
    end
  end

 

  get "site_skel/home"
  match '/home', to: 'site_skel#home'

  get "site_skel/product"
  match '/product', to: 'site_skel#product'
  
  get "site_skel/about"
  match '/about', to: 'site_skel#about'

  get "site_skel/contact"
  match '/contact', to: 'site_skel#contact'

  match '/', to: 'site_skel#home'

  root :to => 'site_skel#home'

end

app/controllers/os_types_controller.rb
class OsTypesController < ApplicationController
  before_filter :authenticate_user!
 
  # GET /os_types
  # GET /os_types.json
  def index
    @os_types = OsType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @os_types, except: [:desc, :created_at, :updated_at] } 
    end
  end

  # GET /os_types/1
  # GET /os_types/1.json
  def show
    @os_type = OsType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @os_type }
    end
  end

  # GET /os_types/new
  # GET /os_types/new.json
  def new
    @os_type = OsType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @os_type }
    end
  end

  # GET /os_types/1/edit
  def edit
    @os_type = OsType.find(params[:id])
  end

  # POST /os_types
  # POST /os_types.json
  def create
    @os_type = OsType.new(params[:os_type])

    respond_to do |format|
      if @os_type.save
        format.html { redirect_to @os_type, notice: 'Os type was successfully created.' }
        format.json { render json: @os_type, status: :created, location: @os_type }
      else
        format.html { render action: "new" }
        format.json { render json: @os_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /os_types/1
  # PUT /os_types/1.json
  def update
    @os_type = OsType.find(params[:id])

    respond_to do |format|
      if @os_type.update_attributes(params[:os_type])
        format.html { redirect_to @os_type, notice: 'Os type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @os_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /os_types/1
  # DELETE /os_types/1.json
  def destroy
    @os_type = OsType.find(params[:id])
    @os_type.destroy

    respond_to do |format|
      format.html { redirect_to os_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/os_types_helper.rb
module OsTypesHelper
end

app/views/os_types/_form.html.haml
= form_for @os_type do |f|
  - if @os_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@os_type.errors.count, "error")} prohibited this os_type from being saved:"
      %ul
        - @os_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :family
    = f.text_field :family
  .field
    = f.label :desc
    = f.text_field :desc
  .actions
    = f.submit 'Save'

app/views/os_types/edit.html.haml
%h1 Editing os_type

= render 'form'

= link_to 'Show', @os_type
\|
= link_to 'Back', os_types_path

app/views/os_types/index.html.haml
%h1 Listing os_types

%table
  %tr
    %th Name
    %th Family
    %th Desc
    %th
    %th
    %th

  - @os_types.each do |os_type|
    %tr
      %td= os_type.name
      %td= os_type.family
      %td= os_type.desc
      %td= link_to 'Show', os_type
      %td= link_to 'Edit', edit_os_type_path(os_type)
      %td= link_to 'Destroy', os_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Os type', new_os_type_path

app/views/os_types/new.html.haml
%h1 New os_type

= render 'form'

= link_to 'Back', os_types_path

app/views/os_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @os_type.name
%p
  %b Family:
  = @os_type.family
%p
  %b Desc:
  = @os_type.desc

= link_to 'Edit', edit_os_type_path(@os_type)
\|
= link_to 'Back', os_types_path