config/routes.rb
OSUPortal::Application.routes.draw do
  resources :flavors

  devise_for :users

  resources :volumes
  resources :volumes do
    collection do
      post 'delete'
      post 'mount'
    end
  end

  resources :flavors
  resources :rules

  resources :rules do
    collection do
      post 'delete'
    end
  end

  resources :key_pairs

  resources :key_pairs do
    collection do
      post 'delete'
    end
  end
  resources :floating_ips

  resources :floating_ips do
    collection do
      post 'addPublicIP'
      post 'addPrivageIP'
      post 'releasePublicIP'
      post 'releasePrivateIP'
      post 'bindIPtoServer'
      post 'unbindIPtoServer'
    end
  end

  resources :securities
  
  resources :securities do
    collection do
      post 'delete'
    end
  end

  resources :images

  resource :images do
    collection do
      post 'delete'
      end
  end

  resources :os_types

  resources :operating_systems

  resources :hosts

  resources :hosts do
    collection do
      post 'start'
      post 'shutdown'
      post 'softreboot'
      post 'hardreboot'
      post 'emergency_login'
      post 'create_image'
      post 'upgrade'
      post 'reinstall'
      post 'delete'
    end
  end

 

  get "site_skel/home"
  match '/home', to: 'site_skel#home'

  get "site_skel/product"
  match '/product', to: 'site_skel#product'
  
  get "site_skel/about"
  match '/about', to: 'site_skel#about'

  get "site_skel/contact"
  match '/contact', to: 'site_skel#contact'

  match '/', to: 'site_skel#home'

  root :to => 'site_skel#home'

end

app/models/image.rb
require 'database_pool'

class Image < Glance

end

app/controllers/images_controller.rb
require 'openstack_activeresource'

class ImagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_openstack_login

  # GET /images
  # GET /images.json
  def index
    @images = OpenStack::Nova::Compute::Image.all
    @servers = OpenStack::Nova::Compute::Server.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = OpenStack::Nova::Compute::Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = OpenStack::Nova::Compute::Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = OpenStack::Nova::Compute::Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = OpenStack::Nova::Compute::Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = OpenStack::Nova::Compute::Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = OpenStack::Nova::Compute::Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
  
  def delete
    params[:ids].each do |imgid|
      OpenStack::Nova::Compute::Image.find(imgid).destroy
    end
    respond_to do |format|
      format.json { render json: { status:  "ok" } }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/images/_image_create.html.haml
#create-image-modal.modal.fade{ "aria-hidden" => "true", "aria-labelledby" => "create-image-lab", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			%form#create-image.form-horizontal{:action => create_image_hosts_path, :method => "POST"}
				.modal-header
					%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
					%h4#create-image-lab.modal-title 制作镜像
				.modal-body

					.form-group
						%label.control-label.col-lg-3{:for => "server_id" } 主机名称 :
						.col-lg-6
							%select#server_id.form-control{:name => "server_id"}
								- @servers.each do |s|
									%option{:value => "#{s.id}"} 
										= s.name
					.form-group
						%label.control-label.col-lg-3{:for => "image_name"}
							%i.red> *
							镜像名称 :
						.col-lg-6
							%input#image_name.form-control{ :name => "image_name",:type => "text"}
					.form-group
						%label.control-label.col-lg-3{:for => "image_desc" }
							%i.red> *
							描述 :
						.col-lg-6
							%textarea#image_desc.form-control{:name => "image_desc", :row => "3"}

					%input{:type=>"hidden", :name=>"authenticity_token", :value=>form_authenticity_token.to_s}

				.modal-footer
					-# %input{:name => "img-create-instance-id", :type => "hidden", :value => ""}
					%input.btn.btn-primary{:type => "submit", :value => "确定"}
					%button.btn.btn-primary{"data-dismiss" => "modal", :type => "text"} 取消

app/views/images/_op_btn.html.haml
#img-toolbar.clearfix
	.btn-group
		%button.btn.btn-primary{ "data-target" => "#create-image-modal", "data-toggle" => "modal" }
			新建
			%i.fa.fa-plus
		= render '/images/image_create' 

	.btn-group
		%button.btn.btn-primary.image_op_btn.disabled{:action => "delete", :href => "#"}
			删除
			%i.fa.fa-trash-o   

	-# .btn-group
	-# 	%a.btn.btn-primary.disabled{:href=> new_host_path, :"data-toggle" => "modal"} 
	-# 		使用镜像创建主机
	-# 		%i.fa.fa-laptop
	
	.btn-group.pull-right
		%a.btn.btn-primary{:href => ""}
			刷新
			%i.fa.fa-refresh

app/views/images/_table.html.haml
.adv-table
	%table#img-table.table.table-bordered.display{ :width => "100%" }
		%thead
			%tr
				%th
				%th 名称
				%th 状态
				%th 进度
				%th 基础镜像
				%th 镜像主机
				%th 创建时间
		%tbody

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%section.panel
	%header.panel-heading
		镜像管理
		%span.tools.pull-right
			%a.fa.fa-chevron-down{:href => "javascript:;"}
			%a.fa.fa-cog{:href => "javascript:;"}
			%a.fa.fa-times{:href => "javascript:;"}
	.panel-body
		#img-tableactionable
			= render 'images/op_btn'
			= render 'images/table'

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path